# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2fef14711ec9a9b2c70d45b93cdd5617474d44ee0ae132b61f73db8278118e4d5b9a920ae05656fc4912709286c6f26cbfbdeb0dd0cca2b0306179f717b7261

test:
  secret_key_base: b764b30d40b703f749ddf0cb02df417cbed82b5eca902e8b6420cc7a083fc4e7fc029c7ebb432f986d2e0590065c8b0b2d152ea26c67430b044a9d842358ac1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
